// Code generated by cacheme, DO NOT EDIT.
package cacheme

import (
	cacheme "github.com/Yiling-J/cacheme-go"

	"github.com/Yiling-J/cacheme-go/integration/cacheme/store"
)

func New(redis cacheme.RedisClient) *store.Client {
	return store.New(redis)
}

func NewCluster(redis cacheme.RedisClient) *store.Client {
	return store.NewCluster(redis)
}
